EscapeRoomWebAppCore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EscapeRoomWebAppCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EscapeRoomWebAppCore/Controllers/EscapeRoomsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EscapeRoomWebAppCore.Data;
using Microsoft.EntityFrameworkCore;

namespace EscapeRoomWebAppCore.Controllers
{
    public class EscapeRoomsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EscapeRoomsController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        [Route("{controller}/{name}")]
        public IActionResult Details(string name)
        {
            return View(_db.EscapeRooms.FirstOrDefault(p=>p.Name==name));
        }

    }
}

EscapeRoomWebAppCore/Controllers/HomeController.cs
using EscapeRoomWebAppCore.Data;
using EscapeRoomWebAppCore.Models;
using EscapeRoomWebAppCore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EscapeRoomWebAppCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(int? diffLevel, int? countPlayers, int? fearLevel, int page = 1)
        {
            int pageSize = 4;

            IQueryable<EscapeRoom> source = _db.EscapeRooms;

            if (diffLevel.HasValue && diffLevel > 0)
                source = source.Where(p => p.DifficultyLevel == diffLevel);

            if (countPlayers.HasValue && (countPlayers > 0 && countPlayers <= 40))
                source = source.Where(p => p.MaximumPlayers >= countPlayers);

            if (fearLevel.HasValue && fearLevel > 0)
                source = source.Where(p => p.FearLevel == fearLevel);


            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).OrderBy(p=>p.Id).ToListAsync();

            PageViewModel pageViewModel = new(count, page, pageSize);
            IndexViewModel viewModel = new()
            {
                PageViewModel = pageViewModel,
                FilterViewModel = new FilterViewModel(countPlayers, diffLevel, fearLevel),
                EscapeRooms = items
            };

            return View(viewModel);
        }

        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

EscapeRoomWebAppCore/Views/Home/Index.cshtml
@model EscapeRoomWebAppCore.ViewModels.IndexViewModel

@{
    ViewData["Title"] = "Index";
}
<style>
    @@font-face {
        font-family: 'FontAwesome';
        src: url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2') format('woff2'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff') format('woff'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf') format('truetype');
        font-weight: normal;
        font-style: normal
    }

    .glyphicon {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale
    }

    .glyphicon-chevron-right:before {
        content: "\f054";
    }

    .glyphicon-chevron-left:before {
        content: "\f053";
    }
</style>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Here you can book escape rooms!</p>
</div>

<form class="d-flex justify-content-end bd-highlight mb-3" method="get">

    <div class="p-2">
        <label>Players: </label>
        <input type="number" name="countPlayers" value="@Model?.FilterViewModel?.MinCountPlayers" class="form-control" min="1" max="30" />
    </div>

    <div class="p-2">
        <label>Difficulty Level: </label>
        <select name="diffLevel" asp-items="Model?.FilterViewModel?.DifficultyLevelList" asp-for="FilterViewModel.DifficultyLevel" class="form-control"></select>
    </div>

    <div class="p-2">
        <label>Fear Level: </label>
        <select name="fearLevel" asp-items="Model?.FilterViewModel?.FearLevelList" asp-for="FilterViewModel.FearLevel" class="form-control"></select>
    </div>

    <div class="mt-auto p-2">
        <input type="submit" value="Filter" class="btn btn-outline-success form-control" />
    </div>

</form>
@if (Model?.EscapeRooms.Count() > 0)
{
    @foreach (var room in Model.EscapeRooms)
    {
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img class="mt-lg-4" style="width:150px; height:auto;" src="data:image/jpeg;base64,@(Convert.ToBase64String(room?.Logotype))" alt="room-logo" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Room - <a asp-action="Details" asp-controller="EscapeRooms" asp-route-name="@room.Name">@room.Name</a></h5>
                        <p class="card-text"><b>DIFFICULTY:</b> @room.DifficultyLevel</p>
                        <p class="card-text"><b>GROUP SIZE:</b> @room.MinimumPlayers - @room.MaximumPlayers</p>
                        <p class="card-text"><b>TIME LIMIT:</b> @room.TimeLimitMinutes minutes</p>

                        <a asp-action="Details" asp-controller="EscapeRooms" asp-route-name="@room.Name" class="btn btn-primary">More info</a>
                        <a href="#" class="btn btn-success">Book</a>
                    </div>
                </div>
            </div>
        </div>
    }
    <page-link page-model="Model.PageViewModel" action="Index"
               page-url-countPlayers="Model?.FilterViewModel?.MinCountPlayers"
               page-url-diffLevel="Model?.FilterViewModel?.DifficultyLevel"
               page-url-fearLevel="Model?.FilterViewModel?.FearLevel"></page-link>
}
else
{
    <p>No rooms yet!</p>
}